export const FETCH_USERCLIENT = "FETCH_USERCLIENT";
export const GET_ALL_PSYCHOLOGIST = "GET_ALL_PSYCHOLOGIST";
export const UPDATE_PSYCHOLOGIST = "UPDATE_PSYCHOLOGIST";
export const DETAILS = "DETAILS";
export const GET_USERCLIENT = 'GET_USERCLIENT';
export const LOCAL_HOST = "http://localhost:3001"