export const LOCAL_HOST = "http://localhost:3001"

export const GET_ALL_PSYCHOLOGIST = "GET_ALL_PSYCHOLOGIST";

//Clear detail state
export const CLEAR = "CLEAR";
export const UPDATE_PSYCHOLOGIST = "UPDATE_PSYCHOLOGIST";
export const DETAILS = "DETAILS";
export const GET_USERCLIENT = 'GET_USERCLIENT';
export const CLEAR_CLIENT = 'CLEAR_CLIENT'
export const FILTER_PSICHOLOGIST_BY_SPECIALTIES = 'FILTER_PSICHOLOGIST_BY_SPECIALTIES';
export const ORDER_PSICHOLOGIST_BY_RATING = 'ORDER_PSICHOLOGIST_BY_RATING';


