export const specialitiesList = [
    'Psicología cognitiva',
    'Psicología clínica',
    'Neuropsicología',
    'Psicología biológica',
    'Psicología comparativa o etología',
    'Psicología educativa',
    'Psicología evolutiva',
    'Psicología del deporte',
    'Psicología jurídica',
    'Psicología de la personalidad',
    'Psicología de la salud',
    'Psicología de pareja',
    'Psicología de familia',
    'Psicología empresarial y organizacional',
    'Psicología militar',
    'Psicología escolar',
    'Psicología gerontológica',
    'Psicología experimental',
    'Psicología del desarrollo',
    'Psicología de ingeniería',
    'Psicología del marketing',
    'Sexología',
    'Psicología comunitaria',
    'Todas las especialidades',
];

